### ISSUE TITLE
protocol5 missing

### ISSUE THREAD

**Issue by LiamFry** [xHasKx/luamqtt#14]
luamqtt fails on Lua 5.1 and 5.3
`/usr/local/bin/lua: /usr/local/share/lua/5.1/mqtt/client.lua:47: module 'mqtt.protocol5' not found:`
`/usr/local/bin/lua: /usr/local/share/lua/5.3/mqtt/client.lua:47: module 'mqtt.protocol5' not found:`

I've used LuaRocks to install luamqtt.
For Lua 5.1 and 5.3, the installation is the same; for 5.2, it's different.
See the attached file.

[luamqtt-version-info.txt](https://github.com/xHasKx/luamqtt/files/3108079/luamqtt-version-info.txt)

One of the odd things is that the installation for Lua 5.2 is also missing `mqtt.protocol5`, but it never complains ... and works. Stranger even is that `mqtt.protocol5` appears in here in GitHub.

**Comment by LiamFry** [comment]
Ok - I've solved 1/2 the problem. It seems that I had `luamqtt` v 1.4.3-4 installed for Lua 5.2; the uninstall/reinstall didn't take, and therefore the example code continued to work. But when i installed `luamqtt` anew for Lua 5.1 and 5.3, it grabbed the latest version, 3.1.0-1 ... which fails with the missing `mqtt.protocol5` complaint.

So ... I now have everything working in Lua 5.1, 5.2, and 5.3 **BUT** they're all using `luamqtt` 1.4.3-4; I cannot get version 3.0.1-1 to work ... with _any_ version of Lua.

**Comment by xHasKx** [comment]
@LiamFry, confirm - there was no entry for mqtt.protocol5 module in luarocks install file, since its creation in the version v3.0, but all tests was ok because of local file loading by require("mqtt.protocol5")

I've rolled up the new version v3.1.0-2 with fixed luarocks file, please try to install again

**Comment by LiamFry** [comment]
w00t! Other than some API changes, it works like a charm. Thanks!
