### ISSUE TITLE
ioloop default args

### ISSUE THREAD

**Issue by dvv** [xHasKx/luamqtt#22]
Hi!

How do I specify own `args` (esp. `timeout`) to default autocreated ioloop?
Can't see how to pass them to https://github.com/xHasKx/luamqtt/blob/master/mqtt/ioloop.lua#L168

TIA

**Comment by dvv** [comment]
I worked this around with
```lua
mqtt.get_ioloop().args.timeout = 0.100
mqtt.run_ioloop(client, loop)
```
If this is the way the issue is done.

**Comment by xHasKx** [comment]
@dvv , I've updated the library version to v3.2.1, better use this:
```lua
local ioloop = require("mqtt.ioloop")
-- ...
ioloop.get(true, {timeout = 0.100})
mqtt.run_ioloop(client)
```

Any feedback appreciated :)

**Comment by dvv** [comment]
Excellent. Thank you!
