### ISSUE TITLE
Broken contract in v5 parser?

### ISSUE THREAD

**Issue by dvv** [xHasKx/luamqtt#25]
https://github.com/xHasKx/luamqtt/blob/master/mqtt/protocol5.lua#L729 -- here `len` could get `false` breaking the comparison with number below and dumping the program.
Please revisit this chunk of code.
TIA

**Comment by xHasKx** [comment]
Hi @dvv ,
thanks for the note, fixed in https://github.com/xHasKx/luamqtt/commit/bd226c0b1a743477e4099f7d270eed9d5bbb493a and bumped version to v3.3.2

**Comment by dvv** [comment]
Thank you!
