### ISSUE TITLE
mqtt over websocket

### ISSUE THREAD

**Issue by kafura-kafiri** [xHasKx/luamqtt#33]
hello, salam, is it possible to make a mqtt connection between browser and lua over websocket

**Comment by xHasKx** [comment]
Hello, are you intended to run Lua in the browser?
There is a way to create websockets connector by yourself: https://github.com/xhaskx/luamqtt#connectors

**Comment by kafura-kafiri** [comment]
Tnx for your reply, i have a react app on browser which only can connect to mqtt on websocket, then on openwrt for server side i only can run lua and i want to connect it to mqtt with websocket protocol. 
so what is the best answer and practice

**Comment by xHasKx** [comment]
If I understand you correct, you have a MQTT broker somewhere accepting connections over websocket protocol, for your react app, and you intended to use the same endpoint to connect openwrt device with luamqtt onboard to the same broker?
In this case the simplest way for you will be to configure additional endpoint on you broker to listen plain mqtt connections, not over websocket.

**Comment by kafura-kafiri** [comment]
Tnx a Lot, you have made my day
