### ISSUE TITLE
connect event when connection fails

### ISSUE THREAD

**Issue by Tieske** [xHasKx/luamqtt#34]
these lines; https://github.com/xHasKx/luamqtt/blob/eacac48e31aa1a58974ef05d76687d8554a33207/mqtt/client.lua#L991:L994

send a "connect" event, when the connection actually fails. Is this intentional or a bug?

**Comment by xHasKx** [comment]
Yes, because CONNACK packet is received and successfully parsed. Client code have to check the .rc property

Check https://github.com/xHasKx/luamqtt/blob/master/examples/simple.lua#L17

**Comment by Tieske** [comment]
thx for the clarification
