### ISSUE TITLE
socket shutdown vs close

### ISSUE THREAD

**Issue by Tieske** [xHasKx/luamqtt#35]
the luasocket connector uses `shutdown`; https://github.com/xHasKx/luamqtt/blob/eacac48e31aa1a58974ef05d76687d8554a33207/mqtt/luasocket.lua#L22

the luasec based luasocket_ssl connector however uses `close`; https://github.com/xHasKx/luamqtt/blob/eacac48e31aa1a58974ef05d76687d8554a33207/mqtt/luasocket_ssl.lua#L45

is there a reason behind these asymmetrical calls?

**Comment by xHasKx** [comment]
When conn.sock is a luasec connection instance - it does not have the :shutdown() method AFAIK

**Comment by xHasKx** [comment]
https://github.com/brunoos/luasec/wiki/LuaSec-1.0.x#conn_close

**Comment by Tieske** [comment]
ah, but the method is available. Sockets are just transparent wrappers around luasocket sockets, so it should have it.

Just isn't documented.

**Comment by Tieske** [comment]
oops... you're right. looked at the close method, but indeed the shutdown is missing. My bad.

**Comment by Tieske** [comment]
see https://github.com/brunoos/luasec/issues/181

**Comment by xHasKx** [comment]
Please note that "close" and "shutdown" can do similar things for plain socket, and completely different actions for SSL sockets. AFAIK, "shutdown" means "do SYN/FIN packets handshake to indicate connection closing", and "close" is just hung up socket on client side. But it's possible that for SSL socket the "close" method is doing the SSL+network handshake, leading to collision with "shutdown"

**Comment by Tieske** [comment]
for now I just updated all to 'close', not perfect but will do I guess.
