### ISSUE TITLE
please confirm one thing---SSL support

### ISSUE THREAD

**Issue by siasjack** [xHasKx/luamqtt#50]
hi  luamqtt is a very good project
i want use it in my openwrt project, but it's seems not support ssl temp
can you confirm ?
and when do you want support SSL

thanks!!

**Comment by Tieske** [comment]
It does support ssl, see `luasocket_ssl.lua`

**Comment by xHasKx** [comment]
@siasjack , you need to install a `luasec` lua module and specify `secure = true` like this: 

https://github.com/xHasKx/luamqtt/blob/cea795eb2a89c24bccc530360cb7a8c3cb15c28a/examples/last-will/client-2.lua#L12

Or in form `secure = {...}` providing a table with luasec ssl parameters like this:

https://github.com/lunarmodules/luasec/blob/5561ddfa3c0a360afafd25cc2bc7b9acbdf5500f/samples/chain/client.lua#L8
