### ISSUE TITLE
openwrt/Makefile error  

### ISSUE THREAD

**Issue by daveliang** [xHasKx/luamqtt#9]
openwrt/Makefile compile error    
last version

**Comment by xHasKx** [comment]
daveliang, can you provide some error output of your make call?

**Comment by daveliang** [comment]
![1552958356(1)](https://user-images.githubusercontent.com/20924987/54573657-2a47b300-4a28-11e9-869c-d7f19c79dd46.jpg)

**Comment by xHasKx** [comment]
Can you post the terminal command you use to build for openwrt?

**Comment by daveliang** [comment]
$make menuconfig 
enable luamqtt
$make package/utils/luamqtt/compile V=s

**Comment by xHasKx** [comment]
daveliang, check the new version of Makefile
Basically, I replaced all spaces with tabs and now commands like yours are not generating any errors.
But I'm not sure you need to compile the package as it's completely written in lua.

And for understanding - the openwrt/Makefile was contributed to my lib, I didn't tested it on real openwrt hardware. So there might be another issues.

**Comment by daveliang** [comment]
I have solved the problem.
